syntax = "proto3";

package gatewayService;

service GatewayService {
  rpc SearchAll(QueryRequest) returns (QueryResponse);
}

message QueryRequest {
    repeated QueryObject queryObjects = 1;
}

message QueryResponse {
    repeated QueryResponseObject results = 2;
}

message QueryObject
{
    uint32 id = 1;
    repeated float vector = 2;
    string bucketString = 3;
    bytes chunk = 4;
    int32 index = 5;
    bool isNeighbour = 6;
}

message QueryResponseObject
{
    uint64 id = 1;
    uint64 id_post = 2;
    float similarity = 3;
    bytes chunk = 4;
    int32 index = 5;
}
