syntax = "proto3";

service SearchVector
{
    rpc Get (SearchVector_Reqs) returns (SearchVector_Results);
}

message SearchVector_Reqs
{
    repeated SearchVector_Req reqs = 1;
}

message SearchVector_Req
{
    uint64 index = 1;

    repeated string bitstrings = 2;
    repeated float vector = 3;

    float minimum_similarity = 4;
    int32 k = 5;
}

message SearchVectorObject
{
    uint64 bucket_id = 1;
    int64 bucket_key = 2;

    float similarity = 3;
    bytes chunk = 2;

    int32 index = 4;
}

message SearchVector_Results
{
    repeated SearchVector_Result results = 1;
}

message SearchVector_Result
{
    repeated SearchVectorObject results = 1;
    string targetIp = 2;
    bool save = 3;
}
