syntax = "proto3";

option csharp_namespace = "GatewayClientServices";

package Client_BatchSearchService;

service Client_BatchSearchService {
  rpc ProcessBytes(ByteArrayRequest) returns (ByteArrayResponse);
}

message Vector
{
    repeated float vec = 1;
}

message ByteArrayRequest {
  repeated Vector vectors = 1;
  int32 topK = 2;
}

message Result {
  float score = 1;
  bytes chunk = 2;
  int32 id = 3;
}

message ResultList {
  repeated Result results = 1;
}

message ByteArrayResponse {
  repeated ResultList resultLists = 1;
}